const MANAGEMENT_KEY = 1;
const ACTION_KEY = 2;
const CLAIM_KEY = 3;
const ENCRYPTION_KEY = 4;

const ECDSA_TYPE = 1;
const RSA_TYPE = 2;

const EXECUTION_TYPE_MANAGEMENT = 0;
const EXECUTION_TYPE_ACTION = 1;

const OPERATION_CALL = 0;
const OPERATION_DELEGATECALL = 1;
const OPERATION_CREATE = 2;


module.exports = {
  MANAGEMENT_KEY,
  ACTION_KEY,
  CLAIM_KEY,
  ENCRYPTION_KEY,
  ECDSA_TYPE,
  RSA_TYPE,
  EXECUTION_TYPE_MANAGEMENT,
  EXECUTION_TYPE_ACTION,
  OPERATION_CALL,
  OPERATION_DELEGATECALL,
  OPERATION_CREATE,
};

