const {MANAGEMENT_KEY, ACTION_KEY, CLAIM_KEY, ENCRYPTION_KEY, ECDSA_TYPE, RSA_TYPE, OPERATION_CALL} = require('./lib/consts.js');

module.exports = {
  MANAGEMENT_KEY, ACTION_KEY, CLAIM_KEY, ENCRYPTION_KEY, ECDSA_TYPE, RSA_TYPE, OPERATION_CALL
};
