const {MANAGEMENT_KEY, ACTION_KEY, CLAIM_KEY, ENCRYPTION_KEY, ECDSA_TYPE, RSA_TYPE} = require('./lib/consts.js');

module.exports = {
  MANAGEMENT_KEY, ACTION_KEY, CLAIM_KEY, ENCRYPTION_KEY, ECDSA_TYPE, RSA_TYPE
};
